---
title: "Abstract"
author: "Zayed Shahjahan"
date: "12/7/2020"
output: 
  github_document: default
  html_document: default
  pdf_document: default
---

<div align="justify"> Obesity is a major health concern in the developed world. This issue is even more pronounced in the United States. Obesity is connected to a host of diseases and the CDC reports that the obesity costs the US economy approximately $149Bn more in added expenditures. This report attempts to analyze the links between income brackets, different forms of physical activity and nutrition in mitigating this public health crisis. Using aggregated state-level data obtained from the CDC, we will perform a multivariate regression analysis. The focus will be in examining conventional wisdom which dictates that healthy eating habits and regular exercise is key to reducing a person’s chance of becoming obese. However, this belief may not hold at the state-level owing to the fallacy of composition which dictates that what is true for an individual may not necessarily be true for the collective. 